// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: message_reversed.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageTwo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageTwo) Reset() {
	*x = MessageTwo{}
	mi := &file_message_reversed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageTwo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageTwo) ProtoMessage() {}

func (x *MessageTwo) ProtoReflect() protoreflect.Message {
	mi := &file_message_reversed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageTwo.ProtoReflect.Descriptor instead.
func (*MessageTwo) Descriptor() ([]byte, []int) {
	return file_message_reversed_proto_rawDescGZIP(), []int{0}
}

func (x *MessageTwo) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type MessageOne struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageOne) Reset() {
	*x = MessageOne{}
	mi := &file_message_reversed_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageOne) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageOne) ProtoMessage() {}

func (x *MessageOne) ProtoReflect() protoreflect.Message {
	mi := &file_message_reversed_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageOne.ProtoReflect.Descriptor instead.
func (*MessageOne) Descriptor() ([]byte, []int) {
	return file_message_reversed_proto_rawDescGZIP(), []int{1}
}

func (x *MessageOne) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_message_reversed_proto protoreflect.FileDescriptor

const file_message_reversed_proto_rawDesc = "" +
	"\n" +
	"\x16message_reversed.proto\x12\x02pb\"\"\n" +
	"\n" +
	"MessageTwo\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\"\n" +
	"\n" +
	"MessageOne\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05valueB\x06Z\x04./pbb\x06proto3"

var (
	file_message_reversed_proto_rawDescOnce sync.Once
	file_message_reversed_proto_rawDescData []byte
)

func file_message_reversed_proto_rawDescGZIP() []byte {
	file_message_reversed_proto_rawDescOnce.Do(func() {
		file_message_reversed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_reversed_proto_rawDesc), len(file_message_reversed_proto_rawDesc)))
	})
	return file_message_reversed_proto_rawDescData
}

var file_message_reversed_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_message_reversed_proto_goTypes = []any{
	(*MessageTwo)(nil), // 0: pb.MessageTwo
	(*MessageOne)(nil), // 1: pb.MessageOne
}
var file_message_reversed_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_message_reversed_proto_init() }
func file_message_reversed_proto_init() {
	if File_message_reversed_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_reversed_proto_rawDesc), len(file_message_reversed_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_reversed_proto_goTypes,
		DependencyIndexes: file_message_reversed_proto_depIdxs,
		MessageInfos:      file_message_reversed_proto_msgTypes,
	}.Build()
	File_message_reversed_proto = out.File
	file_message_reversed_proto_goTypes = nil
	file_message_reversed_proto_depIdxs = nil
}
